// <auto-generated />
using System;
using ChattingApplication.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChattingApplication.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChattingApplication.Models.Group", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("groupAvatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("groupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("groupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("lastMessageTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("createdBy");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ChattingApplication.Models.Message", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("groupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isRead")
                        .HasColumnType("bit");

                    b.Property<string>("timestamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("from");

                    b.HasIndex("groupId");

                    b.HasIndex("to");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ChattingApplication.Models.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<string>("groupsid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("membersid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("groupsid", "membersid");

                    b.HasIndex("membersid");

                    b.ToTable("GroupUser");
                });

            modelBuilder.Entity("ChattingApplication.Models.Group", b =>
                {
                    b.HasOne("ChattingApplication.Models.User", "createdByUser")
                        .WithMany()
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("createdByUser");
                });

            modelBuilder.Entity("ChattingApplication.Models.Message", b =>
                {
                    b.HasOne("ChattingApplication.Models.User", "fromUser")
                        .WithMany("receivedMessages")
                        .HasForeignKey("from")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChattingApplication.Models.Group", "group")
                        .WithMany("messages")
                        .HasForeignKey("groupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChattingApplication.Models.User", "toUser")
                        .WithMany("sentMessages")
                        .HasForeignKey("to")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fromUser");

                    b.Navigation("group");

                    b.Navigation("toUser");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("ChattingApplication.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChattingApplication.Models.User", null)
                        .WithMany()
                        .HasForeignKey("membersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChattingApplication.Models.Group", b =>
                {
                    b.Navigation("messages");
                });

            modelBuilder.Entity("ChattingApplication.Models.User", b =>
                {
                    b.Navigation("receivedMessages");

                    b.Navigation("sentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
